#!/bin/sh
MODULES=$prefix/modules

echo "*** EXECTIME (user) ***"
echo "Now start the realtime process <enter>,"
read junk
$SUDO ./haptuator -Mode -Adaptive -Model 300 0 100 100 -Gamma 10 -Duration 2
#$SUDO ./haptuator  -Mode -Gain 0.0025
echo
echo "Done. Press <enter> to remove the modules."
read junk

